spring.application.name=foro-hub-alura

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/foro_hub_alura
spring.datasource.username=postgres
spring.datasource.password=798116
spring.datasource.driver-class-name=org.postgresql.Driver