CREATE TABLE usuario(
    id bigint primary key generated by default as identity,
    nombre varchar(100) not null,
    correo_electronico varchar(255) not null,
    contrasenia varchar(255) not null
)