CREATE TABLE topico(
    id bigint primary key generated by default as identity,
    titulo VARCHAR(100) not null,
    mensaje VARCHAR(1000) not null,
    fechaCreacion TIMESTAMP not null,
    status boolean default false,
    autor_id bigint references usuario(id) not null,
    curso_id bigint references curso(id) not null
)