CREATE TABLE respuesta(
    id bigint primary key generated by default as identity,
    mensaje varchar(1000) not null,
    topico_id bigint not null references topico(id),
    fecha_creacion timestamp not null,
    autor_id bigint not null references usuario(id),
    solucion boolean default false
)